### ISSUE TITLE
All vanilla biome tags missing except `#minecraft:is_deep_ocean`

### ISSUE THREAD

**Issue by Apollounknowndev** [AlexModGuy/AlexsCaves#107]
None of the biomes are tagged under any vanilla tags excluding `#minecraft:is_deep_ocean`. There are several tags which cave biomes should be in, such as the `is_overworld` tag.

**Comment by AlexModGuy** [comment]
intentional to avoid some overworld generation interfering with caves

**Comment by TelepathicGrunt** [comment]
Re-open this. Overworld biomes must be tagged as overworld for other mods to properly work with it. If you are having issues of other mod’s generation interfering, ask those mods to add a blacklist tag that they will use to avoid your caves. 

Proper classification of biomes is important for modpacks to work. Otherwise this leads to incompatibles and annoyed modders who get bug reports of their stuff not working with yours and they now have to hunt down why your stuff isn’t tagged
