### ISSUE TITLE
Tectonic conflicts with the Abyssal Chasm

### ISSUE THREAD

**Issue by AvengingFish** [AlexModGuy/AlexsCaves#108]
I believe that Tectonic effects the generation of the Abyssal Chasm biome because of the deeper ocean it creates. I added Alex's caves to my modpack and everything seemed smooth at start being that all the cave biomes it provides loaded just fine. But as I tried to see the Abyssal Chasm it wouldn't load the chunk and then it would proceed to freeze everything until I forced task end through task manager.

https://github.com/AlexModGuy/AlexsCaves/assets/146894561/6e58bc4a-a9c4-4617-8869-95231ca178d8

**Comment by Defalting** [comment]
For me it didn't even generate ANY cave biomes, just the underwater one. I think there's an inherent incompatibility with Tectonic, which I hope is eventually cleared by probably an addon.

**Comment by chamops** [comment]
I have yet to encounter this issue with tectonic while using the latest version. No idea if that means I'm lucky or the issue was fixed since AC has had a couple hotfixes, and citadel just had an update that fixes some issues w/ AC biomes not spawning as often in modded biomes. Hopefully I find out the answer to that before I invest any more time in my survival world lol.

**Comment by AlexModGuy** [comment]
update citadel

**Comment by AlexModGuy** [comment]
dupe #794

**Comment by Moctamm** [comment]
For me, the subs and the structures appears but the blocks, corals, worms and every block that should generate doesn't generates. The mobs also do appear except for the hullbreaker and deep ones, the most important ones!! My world is already very progressed I have a lot of farms and the only thing I want from the abyssal chasm are the deep ones; could somebody tell me how to make them spawn so I can get the special items?
