### ISSUE TITLE
Falling blocks are duplicated under sugar rush effect

### ISSUE THREAD

**Issue by Areaphysics** [AlexModGuy/AlexsCaves#1391]
when the sugar rush effect is active, any blocks placed that can fall do so immediately, and begin to rapidly drop themselves over and over, only ending when the effect wears off. The blocks can also not be broken in this state.

https://github.com/user-attachments/assets/c0171c87-b2b3-4e3b-95b2-d63cbcbe1798

**Comment by YocyCraft** [comment]
Dupe #1314 
Anyways, sugar rush effect could cause so many bugs. In some case it could make entity still exist after called `this.discard()` method, which makes some explosive entities explodes multiple times. The current solution for this issue is add `isExploded()` check for each entities one by one…
