### ISSUE TITLE
Map leads to location with no cave biome

### ISSUE THREAD

**Issue by tirelessfrog** [AlexModGuy/AlexsCaves#507]
Even through thorough spectator mode searching of the nearby area, a map I've made directing me to the location of a magnetic cave has taken me to a location without that cave. /locate cites the next nearest cave being more 6000 blocks away. Occurred on a world with William Wythers' Overhauled Overworld in 1.20.1.

**Comment by ZyaTheInfestor** [comment]
Got the same problem on 1.20.1 with "Alex's Caves 1.0.7" installed.

I already encountered this bug 2 weeks ago on "Alex's Caves" 1.0.6 - "Magnetic Caves" map lead me for 10 000 blocks from spawn and there was no Magnetic Caves when I reached the mark.

Dunno if this caused by some mods (even if they are not related with worldgen). For now you may randomly approach any cave type when travelling (found "Abyssal Chasm" when I was swimming to another one marked on a map - of course map lead me to a nowhere so I had to go back for the cave I've skipped).

**Comment by AlexModGuy** [comment]
maps will automatically regenerate in the next version if the coordinates they lead to dont fall inside the biome.

**Comment by VatsaDev** [comment]
The issues still here? the map points to a magnetic cave, hasn't updated, and the nearest one is 3.5k blocks away?

**Comment by Billnotic** [comment]
Also having this issue with magnetic caves, map leads to one that doesn't exist as does /locate. Perhaps this is an issue with tectonic or some other worldgen mod? The primordial caves worked perfectly so I'm not sure.
