### ISSUE TITLE
Cave Centipedes and Murmurs invade the Primordial Caves

### ISSUE THREAD

**Issue by CluckCluckDonalsthe5th** [AlexModGuy/AlexsCaves#528]
In both my regular world and my Single biome Primordial Cave world, There are an **Unholy** amount of Cave Centipedes and Murmurs inside it, Causing immense lag. (I am playing with the Alex Mobs mod too if it wasn't obvious) 

Could you please fix it?

**Comment by AlexModGuy** [comment]
caused by another mod (Alexs Caves Tweaks) because of biome tags I intentionally did not add to my mod. take it up with those devs.

**Comment by CluckCluckDonalsthe5th** [comment]
Oh, Thanks

**Comment by TelepathicGrunt** [comment]
@CluckCluckDonalsthe5th follow my suggestion here https://github.com/TelepathicGrunt/TACT/issues/3#issuecomment-1803533023

@AlexModGuy The issue is not tact. The issue is Alex’s Mobs is not setup properly to spawn those cave mobs at a proper rate in large cave tagged biomes. You will get this issue for any large cave tagged biome from any mod

**Comment by TelepathicGrunt** [comment]
I'll pitch to Neoforge and Fabric to add a `c:no_monster_spawns` or similar named tag in 1.21 Minecraft to make it easier for mob mods to exclude monster-less biomes and make it more obvious that such biomes exists like mushroom biomes and deep dark. 

Also, Deep Dark is tagged as is_cave so your murmurs and and cave centipedes are probably spawning like mad in there unless you manually excluded Deep Dark from your cave tag check in Alex's Mobs
