### ISSUE TITLE
Failed Nuclear Explosion created permanently loaded chunks

### ISSUE THREAD

**Issue by SwiftSniffer** [AlexModGuy/AlexsCaves#630]
Following the detonation of a Nuclear Bomb, and due to messing with its power setting and the fact that it loaded a huge amount of entities and what not (I'll skip the details), this caused the world to crash.

Upon reloading, the explosion did nothing (except a small tnt explosion), and ever since then, all chunks within the bomb radius are permanently loaded.

Removing chunks with the /forceload command did nothing, because apparently no chunks are permanently loaded.
Removing the mod did nothing.

Is there a way to fix that? It hammers the performance of my world. And I can't just delete the world, nor can I do anything about the content of those loaded chunks.

**Comment by SiverDX** [comment]
I haven't used force loaded chunks yet, but won't this (once the unload is called) try to remove non-ticking force loaded chunks?

Shouldn't they be ticking though (since this is what you set them to)?
Meaning, on removal shouldn't be the second parameter still be `true`?
(Since your initial call added the chunks to the `tickingChunks` map)

https://github.com/AlexModGuy/AlexsCaves/blob/1f5b5127757eb6d37793dd0b90e8d6ddff956c46/src/main/java/com/github/alexmodguy/alexscaves/server/entity/item/NuclearExplosionEntity.java#L133-L140

https://github.com/AlexModGuy/AlexsCaves/blob/1f5b5127757eb6d37793dd0b90e8d6ddff956c46/src/main/java/com/github/alexmodguy/alexscaves/server/entity/item/NuclearExplosionEntity.java#L147-L157

```java
        private Map<TicketOwner<T>, LongSet> getTickets(boolean ticking)
        {
            return ticking ? tickingChunks : chunks;
        }

        /**
         * @return {@code true} if the state changed.
         */
        private boolean remove(TicketOwner<T> owner, long chunk, boolean ticking)
        {
            Map<TicketOwner<T>, LongSet> tickets = getTickets(ticking);
            if (tickets.containsKey(owner))
            {
                LongSet ticketChunks = tickets.get(owner);
                if (ticketChunks.remove(chunk))
                {
                    if (ticketChunks.isEmpty())
                        tickets.remove(owner);
                    return true;
                }
            }
            return false;
        }
```

---

Additionally you could also set a callback if I understand it correctly

```java
    /**
     * Sets the forced chunk loading validation callback for the given mod. This allows for validating and removing no longer valid tickets on level load.
     *
     * @apiNote This method should be called from a {@link net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent} using one of the {@link
     * net.minecraftforge.fml.event.lifecycle.ParallelDispatchEvent} enqueueWork methods.
     */
    public static void setForcedChunkLoadingCallback(String modId, LoadingValidationCallback callback)
    {
        if (ModList.get().isLoaded(modId))
            callbacks.put(modId, callback);
        else
            LOGGER.warn("A mod attempted to set the forced chunk validation loading callback for an unloaded mod of id: {}", modId);
    }
```

which is called here:

```java
    /**
     * Reinstates forge's forced chunks when vanilla initially loads a level and reinstates their forced chunks. This method also will validate all of forge's forced
     * chunks using and registered {@link LoadingValidationCallback}.
     *
     * @apiNote Internal
     */
    public static void reinstatePersistentChunks(ServerLevel level, ForcedChunksSavedData saveData)
```

where you can make sure that tickets (force loaded chunks) are removed

**Comment by Solarswordsman3** [comment]
I detonated nuclear bombs in my world before this was fixed, and have since updated to a version where this doesn't happen anymore, however the chunkloading persists, even if I delete the chunks with an external program, is there any way to fix it?

**Comment by SwiftSniffer** [comment]
Maybe try to /forceload remove them? Otherwise you might as well use NBT editor.

**Comment by Solarswordsman3** [comment]
> Maybe try to /forceload remove them? Otherwise you might as well use NBT editor.

/forceload query and /forceload remove do nothing , it's not marked as loaded, but it always is.
where would they be stored in NBT editor, I fully deleted the chunks and the loading persists
