### ISSUE TITLE
[Permission Request] Publish Backported AC to github

### ISSUE THREAD

**Issue by min2222** [AlexModGuy/AlexsCaves#683]
hi, in the previous [thread](https://github.com/AlexModGuy/AlexsCaves/issues/677) you said that AC is depends on new 1.20 features so it wouldn't be complete without them.
but i don't understand, the backport is completed without any bug (as far as i tested) only thing that missing is armor trims, hanging signs, and pottery shards. and they are doesn't affect to game play as much as you think! can you please consider it again?

**Comment by AlexModGuy** [comment]
no. stop opening these issues here in the first place. Our current view is that the mod should only be maintained & released by the developers itself (the code exists here so that people can learn from it, add to it, improve it, and figure out how to do new things with forge). We do not want to grant permission to unofficial ports because inevitably issues with these builds will become issues with the mod in general; which will end up being reported here and will make development even more obtuse. Please respect our wishes if you actually care about this mod in the first place.

**Comment by kitovoi111** [comment]
> no. stop opening these issues here in the first place. Our current view is that the mod should only be maintained & released by the developers itself (the code exists here so that people can learn from it, add to it, improve it, and figure out how to do new things with forge). We do not want to grant permission to unofficial ports because inevitably issues with these builds will become issues with the mod in general; which will end up being reported here and will make development even more obtuse. Please respect our wishes if you actually care about this mod in the first place.

How toxic you are and you don't respect the players, you only do it for yourself. You're a tightwad!
