### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by helpmepleaseeeasdf** [AlexModGuy/AlexsCaves#723]
I Downloaded forge in 1.20.1 and alex's caves in 1.20.1 and it just crashes every time i start the game and idk what to do

**Comment by JustAnotherBugReporter** [comment]
do you have citadel?
Crash log?

**Comment by N1dgey** [comment]
I've ran into the same issue when attempting to run any version of Alex's Caves. Whenever I attempt to open the launcher it crashes after about a second and when the Minecraft Launcher reopens it comes up with Exit Code 1. Exit Code 1 usually indicates something is outdated. I have reinstalled java and updated forge 1.20.1 to the latest version but neither solved the issue.

It is also notable that I am running on a MacBook Pro running on macOS Monterey, Version 12.0.1. If the other person encountering this issue is also using a Mac, or if a similar issue has been encountered before and it has already been established that Alex's Caves simply doesn't run on any Mac device, then please let me know.

**Comment by N1dgey** [comment]
Came back after making a pack and downloading the mod through the forge launcher, I did not realise that Alex's Caves requires Citadel to run, and that was my entire issue.

If you find that you do not have Citadel in your mods folder then here's the link to download the latest version.
https://www.curseforge.com/minecraft/mc-mods/citadel/files/4848887
